version: '3.8'

services:
  king-13:
    image: david-13
    build: .
    ports:
      - '6007:3000'
    environment:
      - MONGO_URI:'mongodb://mongodb:27017/sapient'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
