pipeline {
    agent any
    tools {
        git 'Default'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout your code from Git or any other SCM tool
                git url: 'https://github.com/reshmabojje/Reshma.git'
            }
        }
        
    }

    post {
        success {
            // Actions to perform if the pipeline succeeds
            echo 'Pipeline succeeded!'
        }
        failure {
            // Actions to perform if the pipeline fails
            echo 'Pipeline failed!'
        }
    }
}
